// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AspNetCore10RazorPages.ServiceDefaults.Entities;

public partial class CountryRegionMapping
{
    [Key]
    [StringLength(100)]
    public string Country { get; set; }

    [StringLength(100)]
    public string Region { get; set; }
}